version: '3'

services:
  apache:
    image: 'php:7.4-apache'
    container_name: apache-php
    restart: always
    ports:
      - '9999:80'
    volumes:
      - /root/container/docker-php:/var/www/html

