# -*- mode: ruby -*-
# vi: set ft-ruby

machines = {
	"master" => {"" => 1024, "cpu" => "1", "ip" => "200", "image" => "centos/7"},
	"node-01" => {"" => 1024, "cpu" => "1", "ip" => "201", "image" => "centos/7"},
	"node-02" => {"" => 1024, "cpu" => "1", "ip" => "202", "image" => "centos/7"}
}

Vagrant.configure("2") do |config|
	machines.each do |name, conf|
		config.vm.define "#{name}" do |machine|
			machine.vm.box ="#{conf["image"]}"
			machine.vm.hostname = "#{name}"
			machine.vm.network "public_network", ip: "192.168.114.#{conf["ip"]}"
			machine.vm.provider "vmware" do |vmwareD|
				vmwareD.vmx["ethernet0.pcislotnumber"] = "32"
				vmwareD.gui = false
				vmwareD.name = "#{name}"
				vmwareD.memory = conf["memory"]
				vmwareD.cpus = conf["cpu"]
			end
			
			machine.vm.provision "shell", path: "docker.sh"
			
			if "#{name}" == "master"
				machine.vm.provision "shell", path: "master.sh"
			else
				machine.vm.provision "shell", path: "worker.sh"
			end
			
		end
	end
end